spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/jasperreports
    username: eduardo
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: spring-jasper-reports
