services:
  db:
    container_name: spring-batch-mysql-db
    command: --init-file /data/application/init.sql
    image: mysql
    restart: always
    networks:
      - spring-batch-mysql-net
    volumes:
      - spring-batch-mysql-volume:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

networks:
  spring-batch-mysql-net:
    driver: bridge

volumes:
  spring-batch-mysql-volume: