spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/multitenant
    username: eduardo
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: spring-multitenant