version: '3.9'

services:
  spring-jasper-reports:
    container_name: spring-jasper-reports
    image: postgres
    command: -p 5445
    environment:
      POSTGRES_USER: eduardo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jasperreports
    volumes:
      - spring-jasper-reports-volume:/var/lib/postgresql
    expose:
      - '5445'
    ports:
      - '5445:5445'

volumes:
  spring-jasper-reports-volume:
    name: spring-jasper-reports-volume
